CREATE DATABASE app;

\ c app;

CREATE ROLE app;

GRANT ALL ON DATABASE app TO app;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO app;

CREATE EXTENSION IF NOT EXISTS "pgcrypto";